# Generated by Django 4.2.4 on 2023-09-05 11:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('header', wagtail.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header Size')), ('text', wagtail.blocks.CharBlock(label='Text', max_length=50))])), ('list', wagtail.blocks.StructBlock([('content', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(), label='Items'))])), ('image_text_overlay', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('text', wagtail.blocks.CharBlock(label='Text', max_length=200))])), ('cropped_images_with_text', wagtail.blocks.StructBlock([('image_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('text', wagtail.blocks.CharBlock(label='Text', max_length=200))]), label='Image Item'))])), ('list_with_images', wagtail.blocks.StructBlock([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.blocks.CharBlock(label='Title', max_length=200)), ('text', wagtail.blocks.CharBlock(label='Text', max_length=200)), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=200, required=False)), ('link_url', wagtail.blocks.URLBlock(label='Link URL', max_length=200, required=False))]), label='List Item'))])), ('thumbnail_gallery', wagtail.blocks.StructBlock([('image_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))]), label='Image'))])), ('chart', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Chart Title', label='Title', max_length=120)), ('chart_type', wagtail.blocks.ChoiceBlock(choices=[('bar', 'Bar'), ('horizontalBar', 'Horizontal Bar'), ('pie', 'Pie'), ('doughnut', 'Doughnut'), ('polarArea', 'Polar Area'), ('radar', 'Radar'), ('line', 'Line')], label='Chart Type')), ('labels', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(default='Label', label='Label', max_length=40), label='Chart Labels')), ('datasets', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(default='Dataset #1', label='Dataset Label', max_length=120)), ('dataset_data', wagtail.blocks.ListBlock(wagtail.blocks.IntegerBlock(), default='0', label='Data'))]), label='Dataset'))])), ('map', wagtail.blocks.StructBlock([('marker_title', wagtail.blocks.CharBlock(default="Marker Title 'This will be updated after you save changes.'", max_length=120)), ('marker_description', wagtail.blocks.RichTextBlock()), ('zoom_level', wagtail.blocks.IntegerBlock(default='2', max_value=18, min_value=0, required=False)), ('location_x', wagtail.blocks.FloatBlock(default='35.0', required=False)), ('location_y', wagtail.blocks.FloatBlock(default='0.16', required=False)), ('marker_x', wagtail.blocks.FloatBlock(default='51.5', required=False)), ('marker_y', wagtail.blocks.FloatBlock(default='-0.09', required=False))])), ('image_slider', wagtail.blocks.StructBlock([('image_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))]), label='Image'))]))], blank=True, use_json_field=True),
        ),
    ]
